# Generated by Django 4.0 on 2021-12-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=30, verbose_name='Name of Algorithm')),
                ('timeComplexity', models.CharField(default=' ', max_length=30, verbose_name='Time Complexity')),
                ('spaceComplexity', models.CharField(blank=True, max_length=30, verbose_name='Space Complexity')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
    ]
