# Generated by Django 4.0 on 2021-12-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addAlgo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addalgorithm',
            name='implementation',
            field=models.TextField(blank=True, verbose_name='Implementation'),
        ),
    ]
