# Generated by Django 4.0 on 2021-12-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addAlgo', '0002_addalgorithm_implementation'),
    ]

    operations = [
        migrations.AddField(
            model_name='addalgorithm',
            name='output',
            field=models.TextField(blank=True, verbose_name='Output'),
        ),
    ]
