# Generated by Django 4.0 on 2021-12-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addAlgo', '0004_alter_addalgorithm_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addalgorithm',
            name='output',
            field=models.TextField(blank=True, verbose_name='Output'),
        ),
    ]
