# Generated by Django 4.0 on 2021-12-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addAlgo', '0005_alter_addalgorithm_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='addalgorithm',
            name='applications',
            field=models.CharField(blank=True, max_length=200, verbose_name='Applications'),
        ),
    ]
